packages:
  - packages/*
  - apps/*

catalog:
  '@biomejs/biome': 2.2.4
  '@playwright/test': 1.55.1
  '@tailwindcss/vite': ^4.1.13
  '@types/react': 19.1.14
  '@types/react-dom': 19.1.9
  '@vitest/browser': ^3.2.4
  globals: 16.4.0
  playwright: 1.55.1
  react: 19.1.1
  react-dom: 19.1.1
  tailwindcss: ^4.1.13
  typescript: ^5.9.2
  vitest: ^3.2.4
  vitest-browser-react: ^1.0.1

catalogMode: strict

cleanupUnusedCatalogs: true

gitBranchLockfile: true

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

mergeGitBranchLockfilesBranchPattern:
  - main

overrides:
  '@biomejs/biome': 'catalog:'
  '@playwright/test': 'catalog:'
  '@types/react': 'catalog:'
  '@types/react-dom': 'catalog:'
  globals: 'catalog:'
  playwright: 'catalog:'
  react: 'catalog:'
  react-dom: 'catalog:'
  typescript: 'catalog:'
  vite: npm:rolldown-vite@latest
  vitest: 'catalog:'
