packages:
  - packages/*
  - apps/*

catalog:
  '@biomejs/biome': 2.2.4
  '@playwright/test': 1.55.1
  '@types/react': 19.1.14
  '@types/react-dom': 19.1.9
  '@vitejs/plugin-react': 5.0.3
  globals: 16.4.0
  playwright: 1.55.1
  react: 19.1.1
  react-dom: 19.1.1
  typescript: ^5.9.2

catalogMode: strict

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - esbuild

overrides:
  '@types/react': 'catalog:'
  '@types/react-dom': 'catalog:'
  react: 'catalog:'
  react-dom: 'catalog:'
  vite: npm:rolldown-vite@latest
