packages:
  - packages/*
  - apps/*

catalog:
  '@effect/language-service': ^0.63.2
  '@effect/opentelemetry': ^0.60.0
  '@opentelemetry/exporter-logs-otlp-http': ^0.208.0
  '@opentelemetry/exporter-metrics-otlp-http': ^0.208.0
  '@opentelemetry/exporter-trace-otlp-http': ^0.208.0
  '@opentelemetry/sdk-logs': ^0.208.0
  '@opentelemetry/sdk-metrics': 2.2.0
  '@opentelemetry/sdk-trace-base': ^2.2.0
  '@opentelemetry/sdk-trace-node': ^2.2.0
  '@opentelemetry/sdk-trace-web': ^2.2.0
  '@opentelemetry/semantic-conventions': ^1.38.0
  '@radix-ui/react-slot': ^1.2.4
  '@storybook/react-vite': ^10.1.11
  '@tailwindcss/vite': ^4.1.18
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitest/browser': ^4.0.16
  '@vitest/browser-playwright': ^4.0.16
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  effect: ^3.19.13
  globals: ^16.5.0
  lucide-react: ^0.562.0
  oxlint: ^1.36.0
  oxlint-tsgolint: ^0.10.0
  playwright: ^1.57.0
  prettier: 3.7.4
  prettier-plugin-imports: ^4.3.3
  react: ^19.2.3
  react-dom: ^19.2.3
  storybook: ^10.1.11
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tsdown: ^0.18.3
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vite: npm:rolldown-vite@7.2.2
  vite-tsconfig-paths: 6.0.3
  vitest: ^4.0.16
  vitest-browser-react: ^2.0.2
  web-vitals: ^5.1.0

catalogMode: strict

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - protobufjs

mergeGitBranchLockfilesBranchPattern:
  - main

overrides:
  glog: 10.5.0
  '@oxc-project/types': 0.94.0
  '@storybook/react-vite': 'catalog:'
  '@types/react': 'catalog:'
  '@types/react-dom': 'catalog:'
  globals: 'catalog:'
  lightningcss: 1.30.1
  playwright: 'catalog:'
  react: 'catalog:'
  react-dom: 'catalog:'
  storybook: 'catalog:'
  typescript: 'catalog:'
  vite: npm:rolldown-vite@latest
  vitest: 'catalog:'
