packages:
  - packages/*
  - apps/*

catalog:
  '@biomejs/biome': 2.2.4
  '@radix-ui/react-slot': ^1.2.3
  '@storybook/react-vite': 10.0.0-beta.10
  '@tailwindcss/vite': ^4.1.13
  '@types/react': 19.1.14
  '@types/react-dom': 19.1.9
  '@vitest/browser': ^3.2.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  globals: 16.4.0
  lucide-react: ^0.544.0
  playwright: 1.55.1
  react: 19.1.1
  react-dom: 19.1.1
  storybook: 10.0.0-beta.7
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.13
  tsdown: ^0.15.5
  tw-animate-css: ^1.4.0
  typescript: ^5.9.2
  vite-tsconfig-paths: 6.0.0-beta.4
  vitest: ^3.2.4
  vitest-browser-react: ^1.0.1

catalogMode: strict

cleanupUnusedCatalogs: true

gitBranchLockfile: true

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

mergeGitBranchLockfilesBranchPattern:
  - main

overrides:
  '@biomejs/biome': 'catalog:'
  '@storybook/react-vite': 'catalog:'
  '@types/react': 'catalog:'
  '@types/react-dom': 'catalog:'
  globals: 'catalog:'
  playwright: 'catalog:'
  react: 'catalog:'
  react-dom: 'catalog:'
  storybook: 'catalog:'
  typescript: 'catalog:'
  vite: npm:rolldown-vite@7.1.16
  vitest: 'catalog:'
