packages:
  - packages/*
  - apps/*

catalog:
  "@effect/language-service": ^0.67.0
  "@effect/opentelemetry": ^0.60.0
  "@opentelemetry/exporter-logs-otlp-http": ^0.210.0
  "@opentelemetry/exporter-metrics-otlp-http": ^0.210.0
  "@opentelemetry/exporter-trace-otlp-http": ^0.210.0
  "@opentelemetry/sdk-logs": ^0.210.0
  "@opentelemetry/sdk-metrics": 2.4.0
  "@opentelemetry/sdk-trace-base": ^2.4.0
  "@opentelemetry/sdk-trace-node": ^2.4.0
  "@opentelemetry/sdk-trace-web": ^2.4.0
  "@opentelemetry/semantic-conventions": ^1.39.0
  "@radix-ui/react-slot": ^1.2.4
  "@storybook/react-vite": ^10.1.11
  "@tailwindcss/vite": ^4.1.18
  "@types/react": ^19.2.8
  "@types/react-dom": ^19.2.3
  "@vitest/browser": ^4.0.17
  "@vitest/browser-playwright": ^4.0.17
  "@vitest/browser-preview": ^4.0.17
  "@vitest/coverage-v8": ^4.0.17
  "@vitest/ui": ^4.0.17
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  effect: ^3.19.14
  globals: ^17.0.0
  lucide-react: ^0.562.0
  oxfmt: ^0.24.0
  oxlint: ^1.39.0
  oxlint-tsgolint: ^0.11.1
  playwright: ^1.57.0
  react: ^19.2.3
  react-dom: ^19.2.3
  storybook: ^10.1.11
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.16
  tsdown: 0.20.0-beta.3
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vite-tsconfig-paths: 6.0.4
  vitest: ^4.0.17
  vitest-browser-react: ^2.0.2
  web-vitals: ^5.1.0
  vite: ^8.0.0-beta.0

catalogMode: strict

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - msgpackr-extract
  - protobufjs

mergeGitBranchLockfilesBranchPattern:
  - main

overrides:
  vite: 8.0.0-beta.0
  rolldown: 1.0.0-beta.60
