packages:
  - packages/*
  - apps/*

catalog:
  '@effect/language-service': ^0.73.0
  '@effect/opentelemetry': ^0.61.0
  '@opentelemetry/exporter-logs-otlp-http': ^0.211.0
  '@opentelemetry/exporter-metrics-otlp-http': ^0.211.0
  '@opentelemetry/exporter-trace-otlp-http': ^0.211.0
  '@opentelemetry/sdk-logs': ^0.211.0
  '@opentelemetry/sdk-metrics': 2.5.0
  '@opentelemetry/sdk-trace-base': ^2.5.0
  '@opentelemetry/sdk-trace-node': ^2.5.0
  '@opentelemetry/sdk-trace-web': ^2.5.0
  '@opentelemetry/semantic-conventions': ^1.39.0
  '@radix-ui/react-slot': ^1.2.4
  '@storybook/react-vite': ^10.2.6
  '@tailwindcss/vite': ^4.1.18
  '@types/react': ^19.2.13
  '@types/react-dom': ^19.2.3
  '@vitest/browser': ^4.0.18
  '@vitest/browser-playwright': ^4.0.18
  '@vitest/browser-preview': ^4.0.18
  '@vitest/coverage-v8': ^4.0.18
  '@vitest/ui': ^4.0.18
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  effect: ^3.19.16
  globals: ^17.3.0
  lucide-react: ^0.563.0
  oxfmt: ^0.28.0
  oxlint: ^1.43.0
  oxlint-tsgolint: ^0.11.4
  playwright: ~1.56.1
  react: ^19.2.4
  react-dom: ^19.2.4
  storybook: ^10.2.6
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.16
  tsdown: 0.20.3
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vite-tsconfig-paths: 6.0.5
  vitest: ^4.0.18
  vitest-browser-react: ^2.0.5
  web-vitals: ^5.1.0

catalogMode: strict

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - protobufjs

mergeGitBranchLockfilesBranchPattern:
  - main

overrides:
  rolldown: 1.0.0-rc.3
  vite: 8.0.0-beta.13
