packages:
  - packages/*
  - apps/*

catalog:
  '@radix-ui/react-slot': ^1.2.3
  '@storybook/react-vite': ^10.0.0-rc.3
  '@tailwindcss/vite': ^4.1.16
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@vitest/browser': ^4.0.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  globals: ^16.4.0
  lucide-react: ^0.548.0
  oxlint: ^1.24.0
  oxlint-tsgolint: ^0.3.0
  playwright: ^1.56.1
  prettier: 3.6.2
  prettier-plugin-imports: ^4.3.3
  react: ^19.2.0
  react-dom: ^19.2.0
  storybook: ^10.0.0-rc.3
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.16
  tsdown: ^0.15.10
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vite-tsconfig-paths: ^6.0.0-beta.4
  vitest: ^4.0.4
  vitest-browser-react: ^2.0.2

catalogMode: strict

cleanupUnusedCatalogs: true

gitBranchLockfile: true

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

mergeGitBranchLockfilesBranchPattern:
  - main

overrides:
  '@oxc-project/types': 0.94.0
  '@storybook/react-vite': 'catalog:'
  '@types/react': 'catalog:'
  '@types/react-dom': 'catalog:'
  globals: 'catalog:'
  lightningcss: 1.30.1
  playwright: 'catalog:'
  react: 'catalog:'
  react-dom: 'catalog:'
  storybook: 'catalog:'
  typescript: 'catalog:'
  vite: npm:rolldown-vite@7.1.17
  vitest: 'catalog:'
