name: "Pipeline"
on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  ci:
    name: "CI"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
        with:
          fetch-depth: 0
      - uses: "moonrepo/setup-toolchain@v0"
        with:
          auto-install: true

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - run: "moon ci"

      - name: "Collect/retrospect on results"
        uses: "appthrust/moon-ci-retrospect@v2"
        if: success() || failure()

      - uses: "moonrepo/run-report-action@v1"
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
